theme: "hugo-PaperMod"
baseURL: https://statistix.be/
languageCode: en-us
title: statistix

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true
          
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: statistix
    description: "Landing page of statistix.be"
    keywords: [Landing page]
    author: Antoine Soetewey
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false
    
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    label:
        text: "statistix"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: statistix
        buttons:
            - name: Personal website
              url: "https://antoinesoetewey.com/"
            - name: Blog
              url: https://statsandr.com/

    socialIcons:
        - name: twitter
          url: "https://twitter.com/statsandr"
        - name: github
          url: "https://github.com/AntoineSoetewey"
        - name: link
          url: "https://easystat.be/"
        - name: link
          url: "https://datanalyze.be/"
          
    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]